name: "trt_fp_16"
platform: "tensorrt_plan"
dynamic_batching { }

max_batch_size: 1024
input {
    name: "input"
    data_type: TYPE_FP32
    dims: [3,224,224]
}

output {
    name: "output"
    data_type: TYPE_FP32
    dims: [1000]
}

instance_group [
    {
        count: 1
        kind: KIND_GPU
        gpus: [0]
    }
]

default_model_filename: "model.plan"
